<template>
  <div class="loader">
    <div class="loadingio-spinner-spinner-pxhwiz4dvf9">
      <div class="ldio-c7jd9nd7onm">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "v-loader"
};
</script>

<style scoped>
.loader {
  display: flex;
  justify-content: center;
  align-items: center;
}
@keyframes ldio-c7jd9nd7onm {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
.ldio-c7jd9nd7onm div {
  left: 94px;
  top: 48px;
  position: absolute;
  animation: ldio-c7jd9nd7onm linear 0.8403361344537814s infinite;
  background: #db4c3f;
  width: 12px;
  height: 24px;
  border-radius: 6px / 12px;
  transform-origin: 6px 52px;
}
.ldio-c7jd9nd7onm div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.7703081232492996s;
  background: #db4c3f;
}
.ldio-c7jd9nd7onm div:nth-child(2) {
  transform: rotate(30deg);
  animation-delay: -0.7002801120448179s;
  background: #db4c3f;
}
.ldio-c7jd9nd7onm div:nth-child(3) {
  transform: rotate(60deg);
  animation-delay: -0.6302521008403361s;
  background: #db4c3f;
}
.ldio-c7jd9nd7onm div:nth-child(4) {
  transform: rotate(90deg);
  animation-delay: -0.5602240896358543s;
  background: #db4c3f;
}
.ldio-c7jd9nd7onm div:nth-child(5) {
  transform: rotate(120deg);
  animation-delay: -0.49019607843137253s;
  background: #db4c3f;
}
.ldio-c7jd9nd7onm div:nth-child(6) {
  transform: rotate(150deg);
  animation-delay: -0.4201680672268907s;
  background: #db4c3f;
}
.ldio-c7jd9nd7onm div:nth-child(7) {
  transform: rotate(180deg);
  animation-delay: -0.35014005602240894s;
  background: #db4c3f;
}
.ldio-c7jd9nd7onm div:nth-child(8) {
  transform: rotate(210deg);
  animation-delay: -0.2801120448179272s;
  background: #db4c3f;
}
.ldio-c7jd9nd7onm div:nth-child(9) {
  transform: rotate(240deg);
  animation-delay: -0.21008403361344535s;
  background: #db4c3f;
}
.ldio-c7jd9nd7onm div:nth-child(10) {
  transform: rotate(270deg);
  animation-delay: -0.1400560224089636s;
  background: #db4c3f;
}
.ldio-c7jd9nd7onm div:nth-child(11) {
  transform: rotate(300deg);
  animation-delay: -0.0700280112044818s;
  background: #db4c3f;
}
.ldio-c7jd9nd7onm div:nth-child(12) {
  transform: rotate(330deg);
  animation-delay: 0s;
  background: #db4c3f;
}
.loadingio-spinner-spinner-pxhwiz4dvf9 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-c7jd9nd7onm {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-c7jd9nd7onm div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
